version: '3.8'

services:
  db:
    image: postgres
    container_name: pg_planmytrip
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planmytrip
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - planmytrip_net

  backend:
    build: ./backend
    container_name: backend_planmytrip
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/planmytrip
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - planmytrip_net

  frontend:
    build: ./frontend
    container_name: frontend_planmytrip
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - planmytrip_net
    command: npm run dev -- --host

networks:
  planmytrip_net:
